// Archivo de configuración de firebase
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6sxHyzMcrcc_8CuRvxFP1DigmqIlGDQ',
    appId: '1:589297709005:web:68da312ac1d5043884de84',
    messagingSenderId: '589297709005',
    projectId: 'lista-compra-53ede',
    authDomain: 'lista-compra-53ede.firebaseapp.com',
    storageBucket: 'lista-compra-53ede.firebasestorage.app',
    measurementId: 'G-5NVRYM2W1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzMb7Y4-2pkbj9LYPW9VjdIdNb2EK1ybY',
    appId: '1:589297709005:android:6654e31195ff83b784de84',
    messagingSenderId: '589297709005',
    projectId: 'lista-compra-53ede',
    storageBucket: 'lista-compra-53ede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKCqMPgY9CXf0aLYoSXKBndnwc_h_Z9RQ',
    appId: '1:589297709005:ios:6ce809a177f96e5784de84',
    messagingSenderId: '589297709005',
    projectId: 'lista-compra-53ede',
    storageBucket: 'lista-compra-53ede.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKCqMPgY9CXf0aLYoSXKBndnwc_h_Z9RQ',
    appId: '1:589297709005:ios:6ce809a177f96e5784de84',
    messagingSenderId: '589297709005',
    projectId: 'lista-compra-53ede',
    storageBucket: 'lista-compra-53ede.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC6sxHyzMcrcc_8CuRvxFP1DigmqIlGDQ',
    appId: '1:589297709005:web:8549ac3b9ec54fdd84de84',
    messagingSenderId: '589297709005',
    projectId: 'lista-compra-53ede',
    authDomain: 'lista-compra-53ede.firebaseapp.com',
    storageBucket: 'lista-compra-53ede.firebasestorage.app',
    measurementId: 'G-G27K6542EX',
  );
}
